<div class="space-y-6">
    <header class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
        <div><p class="text-xs font-bold uppercase tracking-[0.16em] text-teal-300">{{ $isSaasView ? 'Platform control' : 'Operations overview' }}</p><h1 class="mt-2 text-2xl font-black text-white sm:text-3xl">{{ $workspaceName }}</h1><p class="mt-2 text-sm text-slate-500">{{ $isSaasView ? 'Manage tenants, access, and accountable platform activity.' : 'Live billing, customer, and network activity.' }}</p></div>
        <div class="flex items-center gap-2 text-xs text-slate-500"><span class="h-2 w-2 rounded-full bg-emerald-400"></span>Updated {{ now()->format('M d, H:i') }}</div>
    </header>

    @if($activeAnnouncements->isNotEmpty())
        <section class="space-y-3">
            @foreach($activeAnnouncements as $announcement)
                <div class="border border-teal-300/25 bg-teal-300/10 p-4" style="border-radius:6px">
                    <div class="flex items-center gap-2 text-xs font-bold uppercase tracking-wide text-teal-300"><span aria-hidden="true">📣</span>{{ ucfirst($announcement->type) }} announcement</div>
                    <p class="mt-1 font-bold text-white">{{ $announcement->title }}</p>
                    <p class="mt-1 text-sm text-slate-300">{{ $announcement->body }}</p>
                </div>
            @endforeach
        </section>
    @endif

    <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        @if($isSaasView)
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Active tenants</p><p class="mt-4 text-3xl font-black text-white">{{ number_format($metrics['tenants']) }}</p><p class="mt-3 text-sm text-amber-300">{{ $metrics['trial_tenants'] }} trial · {{ $metrics['suspended_tenants'] }} suspended</p></div>
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">SaaS MRR</p><p class="mt-4 text-3xl font-black text-white">৳{{ number_format($metrics['saas_mrr'], 2) }}</p><p class="mt-3 text-sm text-teal-300">৳{{ number_format($metrics['saas_arr'], 2) }} ARR</p></div>
        @endif
        <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Customers</p><p class="mt-4 text-3xl font-black text-white">{{ number_format($metrics['customers']) }}</p><p class="mt-3 text-sm text-emerald-300">{{ $metrics['active_services'] }}% active</p></div>
        @if($isSaasView)
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Expiring soon</p><p class="mt-4 text-3xl font-black text-white">{{ number_format($metrics['subscriptions_expiring']) }}</p><p class="mt-3 text-sm text-slate-500">Next 30 days</p></div>
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">SaaS collected</p><p class="mt-4 text-3xl font-black text-white">৳{{ number_format($metrics['saas_collected_this_month'], 2) }}</p><p class="mt-3 text-sm text-slate-500">This month</p></div>
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">SaaS outstanding</p><p class="mt-4 text-3xl font-black text-white">৳{{ number_format($metrics['saas_outstanding'], 2) }}</p><p class="mt-3 text-sm text-amber-300">{{ $metrics['saas_overdue_count'] }} overdue</p></div>
        @else
            <div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Collected this month</p><p class="mt-4 text-3xl font-black text-white">৳{{ number_format($metrics['monthly_revenue'], 2) }}</p><p class="mt-3 text-sm text-slate-500">Successful payments</p></div>
        @endif
        @unless($isSaasView)<div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Open invoices</p><p class="mt-4 text-3xl font-black text-white">{{ number_format($metrics['pending_billing']) }}</p><p class="mt-3 text-sm text-amber-300">৳{{ number_format($metrics['outstanding'], 2) }} billed</p></div>@endunless
        @unless($isSaasView)<div class="bc-panel p-5" style="border-radius: 8px"><p class="text-xs font-bold uppercase text-slate-500">Online devices</p><p class="mt-4 text-3xl font-black text-white">{{ $metrics['online_devices'] }}</p><p class="mt-3 text-sm text-teal-300">Network inventory</p></div>@endunless
    </section>

    @if($isSaasView)
    <section class="grid gap-5 xl:grid-cols-[0.8fr_1.2fr]">
        <div class="bc-panel p-5 sm:p-6" style="border-radius: 8px"><h2 class="font-bold text-white">Platform controls</h2><div class="mt-5 space-y-2"><a href="{{ route('tenants') }}" class="flex items-center justify-between border border-white/10 p-4 hover:border-teal-300/30 hover:bg-teal-300/5" style="border-radius: 6px"><span><span class="block font-bold text-white">Tenant portfolio</span><span class="mt-1 block text-xs text-slate-500">Provision, suspend, edit, or enter a workspace</span></span><span class="text-teal-300">→</span></a><a href="{{ route('saas-plans') }}" class="flex items-center justify-between border border-white/10 p-4 hover:border-teal-300/30 hover:bg-teal-300/5" style="border-radius: 6px"><span><span class="block font-bold text-white">SaaS plans</span><span class="mt-1 block text-xs text-slate-500">Manage pricing, trials, limits, and grace</span></span><span class="text-teal-300">→</span></a><a href="{{ route('platform-users') }}" class="flex items-center justify-between border border-white/10 p-4 hover:border-teal-300/30 hover:bg-teal-300/5" style="border-radius: 6px"><span><span class="block font-bold text-white">Users and roles</span><span class="mt-1 block text-xs text-slate-500">Control platform and tenant access</span></span><span class="text-teal-300">→</span></a><a href="{{ route('audit-activity') }}" class="flex items-center justify-between border border-white/10 p-4 hover:border-teal-300/30 hover:bg-teal-300/5" style="border-radius: 6px"><span><span class="block font-bold text-white">Audit activity</span><span class="mt-1 block text-xs text-slate-500">Review accountable actions across tenants</span></span><span class="text-teal-300">→</span></a></div></div>
        <div class="bc-panel p-5 sm:p-6" style="border-radius: 8px"><div class="mb-5 flex items-center justify-between"><h2 class="font-bold text-white">Recent platform activity</h2><a href="{{ route('audit-activity') }}" class="text-sm font-semibold text-teal-300">View audit log</a></div><div>@forelse($recentAuditActivity as $log)<div class="flex items-center justify-between gap-4 border-b border-white/5 py-3 last:border-0"><div class="min-w-0"><div class="truncate text-sm font-semibold text-white">{{ str_replace('.', ' · ', $log->action) }}</div><div class="mt-1 truncate text-xs text-slate-600">{{ $log->user?->name ?? 'System' }} · {{ $log->tenant?->name ?? 'Platform' }}</div></div><time class="shrink-0 text-xs text-slate-600">{{ $log->created_at->diffForHumans() }}</time></div>@empty<p class="py-10 text-center text-sm text-slate-600">No platform activity recorded yet.</p>@endforelse</div></div>
    </section>
    @else
    <section class="grid gap-5 xl:grid-cols-2">
        <div class="bc-panel p-5 sm:p-6" style="border-radius: 8px"><div class="mb-5 flex items-center justify-between"><h2 class="font-bold text-white">Recent collections</h2>@unless($isSaasView)<a href="{{ route('payments') }}" class="text-sm font-semibold text-teal-300">View payments</a>@endunless</div><div class="space-y-1">@forelse($recentPayments as $payment)<div class="flex items-center justify-between border-b border-white/5 py-3 last:border-0"><div class="min-w-0"><div class="truncate text-sm font-semibold text-white">{{ $payment->customer?->name ?? 'Customer' }}</div><div class="text-xs text-slate-600">{{ $payment->invoice?->invoice_number ?? strtoupper($payment->payment_method) }} · {{ $payment->payment_date->format('M d, H:i') }}</div></div><div class="ml-4 text-sm font-black text-emerald-300">+৳{{ number_format($payment->amount, 2) }}</div></div>@empty<p class="py-10 text-center text-sm text-slate-600">No collections in this workspace yet.</p>@endforelse</div></div>
        <div class="bc-panel p-5 sm:p-6" style="border-radius: 8px"><div class="mb-5 flex items-center justify-between"><h2 class="font-bold text-white">Overdue queue</h2>@unless($isSaasView)<a href="{{ route('billing') }}" class="text-sm font-semibold text-teal-300">Open billing</a>@endunless</div><div class="space-y-1">@forelse($overdueInvoices as $invoice)<div class="flex items-center justify-between border-b border-white/5 py-3 last:border-0"><div class="min-w-0"><div class="truncate text-sm font-semibold text-white">{{ $invoice->customer?->name ?? 'Deleted customer' }}</div><div class="text-xs text-slate-600">{{ $invoice->invoice_number }} · Due {{ $invoice->due_date?->format('M d') }}</div></div><div class="ml-4 text-sm font-black text-rose-300">৳{{ number_format($invoice->outstanding_amount, 2) }}</div></div>@empty<p class="py-10 text-center text-sm text-slate-600">No overdue invoices.</p>@endforelse</div></div>
    </section>
    @endif
</div>